# Build settings
[build]
  publish = "dist"
  command = "npm run build"

# Ensure the site always serves index.html for Single Page Applications (SPA)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Handle assets
[[redirects]]
  from = "/assets/*"
  to = "/assets/:splat"
  status = 200
  force = true

# Handle 404s
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 404
